### ISSUE TITLE
多tab切换需要重新登陆

### ISSUE THREAD

**Issue by liuxiaoyue** [YaoApp/xgen-deprecated#2]
您好
内置的界面管理系统登陆成功之后返回的token存在了seesionStorage里，每个请求登陆校验的时候前端页面从seesionStorage里拿token传参数给后端，导致在多个tab下登陆失效.
请问如上描述设计的初衷是? 是否可以把这个登陆态放到cookie里 ，这样前后端的关联性也没有那么强。假如可以放到cookie中，需要改写登陆逻辑，重新编写一个自定义处理器，这个是我的想法，不知道是否有更好的建议?

**Comment by MatrixAge** [comment]
Auth用的JWT（JSON Web Token），放在cookie里不合适，存在安全隐患。

后面的版本会考虑在app.json中支持自定义token存储方式和过期时间：SessionStorage/LocalStorage

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/172361193-7aaaece9-0511-4ee7-a69c-71f8c9d4832d.png)

这个feature将会在Yao 0.9.2 xgen 1.0.0 释出。
