### ISSUE TITLE
When Dynamiclist uses the datepicker component, clicking OK will blank the screen

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/xgen-deprecated#3]
<img width="411" alt="Lt6AR2F6Bz" src="https://user-images.githubusercontent.com/34130829/173042263-fda4ead2-b65f-430c-b6c3-c3bba59fd67c.png">

**Comment by MatrixAge** [comment]
It should be the problem of format conversion. First, use the input+placeholder prompt as an alternative.

I'll let you know when this problem is fixed.
