### ISSUE TITLE
When multiple records are added to the dynamic list, the page does not respond

### ISSUE THREAD

**Issue by tengzhuofei** [YaoApp/xgen-deprecated#6]
![image](https://user-images.githubusercontent.com/49179198/181405700-0b9f231f-f244-4329-9c6f-0b3c1f41b9a0.png)

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/181405869-f49fba93-75fa-41aa-bf27-0fc18fca5698.png)

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/181406006-54e33a9f-880c-45dc-8bae-aaa1050c26c9.png)

**Comment by MatrixAge** [comment]
这个样式问题已经修复了，但0.9.1的yao未打包最新版本的xgen

**Comment by tengzhuofei** [comment]
那我用0.9.2版本

**Comment by tengzhuofei** [comment]
0.9.2也不行啊？ xgen我用的最新的
